// Battle Brothers Event Requirements Database
// Total events: 35

this.EventRequirements <- [
    {
        EventID = "event.arena_tournament",
        FileName = "arena_tournament_event.nut",
        RequiredDLC = ["Blazing Deserts"],
        SettlementSituation = "Must have Arena Tournament Settlement Situation",
        SettlementType = "Southern",
        TileRequirements = { Road = "OnRoad", OnOrBelowYLine = 60 },
    },
    {
        EventID = "event.belly_dancer",
        FileName = "belly_dancer_event.nut",
        MaxDistanceFromSettlement = 4,
        MinimumCrowns = 751,
        MustHaveOpenRosterSpace = true,
        RequiredDLC = ["Blazing Deserts"],
        SettlementMustNotBeHostile = true,
        SettlementType = "Southern",
        TimeOfDay = "Day",
    },
    {
        EventID = "event.cannon_execution",
        FileName = "cannon_execution_event.nut",
        MustHaveOpenRosterSpace = true,
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert", TacticalType = "DesertHills", Road = "OnRoad" },
    },
    {
        EventID = "event.cultish_arrangement",
        FileName = "cultish_arrangement_event.nut",
        MinDistanceFromSettlement = 8,
        MinimumDays = 11,
        NumberOfEmptyInventorySlots = 1,
        PlayerCharacterExcluded = true,
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert" },
        TimeOfDay = "Night",
    },
    {
        EventID = "event.cultural_conflagration",
        FileName = "cultural_conflagration_event.nut",
        MinimumBrotherCount = 6,
        RequiredDLC = ["Blazing Deserts"],
        SpecialConsiderations = ["Must have at least 1 southern and 1 northern ethnicity bros."],
    },
    {
        EventID = "event.desert_bugbite",
        FileName = "desert_bugbite_event.nut",
        MinDistanceFromSettlement = 6,
        RequiredDLC = ["Blazing Deserts"],
        RequiredRetinue = ["follower.scout"],
        TileRequirements = { Road = "OffRoad", TerrainType = "Desert" },
        UnhandledLines = ["if (bro.getSkills().hasSkill(\"effects.exhausted\"))", "if (bro.getSkills().hasSkill(\"trait.strong\"))", "if (bro.getSkills().hasSkill(\"trait.tough\"))", "if (bro.getSkills().hasSkill(\"trait.lucky\"))", "if (bro.m.Ethnicity == 1)", "if (chance < lowestChance)", "if (lowestBro == null)"],
    },
    {
        EventID = "event.desert_fall",
        FileName = "desert_fall_event.nut",
        MinDistanceFromSettlement = 6,
        RequiredDLC = ["Blazing Deserts"],
        RequiredRetinue = ["follower.scout"],
        TileRequirements = { Road = "OffRoad", TerrainType = "Desert" },
        UnhandledLines = ["if (bro.getSkills().hasSkill(\"injury.bruised_leg\"))", "if (bro.getSkills().hasSkill(\"trait.strong\"))", "if (bro.getSkills().hasSkill(\"trait.tough\"))", "if (bro.getSkills().hasSkill(\"trait.lucky\"))", "if (bro.m.Ethnicity == 1)", "if (chance < lowestChance)", "if (lowestBro == null)"],
    },
    {
        EventID = "event.desert_feet",
        ExcludedOrigins = ["scenario.southern_quickstart", "scenario.manhunters"],
        FileName = "desert_feet_event.nut",
        MinDistanceFromSettlement = 6,
        RequiredDLC = ["Blazing Deserts"],
        RequiredRetinue = ["follower.scout"],
        TileRequirements = { Road = "OffRoad", TerrainType = "Desert" },
        UnhandledLines = ["if (bro.m.Ethnicity == 1)", "if (numNortherners < 3)"],
    },
    {
        EventID = "event.desert_heat",
        FileName = "desert_heat_event.nut",
        MinDistanceFromSettlement = 6,
        RequiredDLC = ["Blazing Deserts"],
        RequiredRetinue = ["follower.scout"],
        TileRequirements = { TerrainType = "Desert" },
        TimeOfDay = "Day",
        UnhandledLines = ["if (bro.getSkills().hasSkill(\"effects.exhausted\"))", "if (bro.getSkills().hasSkill(\"trait.strong\"))", "if (bro.getSkills().hasSkill(\"trait.tough\"))", "if (bro.getSkills().hasSkill(\"trait.lucky\"))", "if (bro.m.Ethnicity == 1)", "if (chance < lowestChance)", "if (lowestBro == null)"],
    },
    {
        EventID = "event.desert_sand",
        FileName = "desert_sand_event.nut",
        MinDistanceFromSettlement = 6,
        RequiredDLC = ["Blazing Deserts"],
        RequiredRetinue = ["follower.scout"],
        TileRequirements = { TerrainType = "Desert", Road = "OffRoad" },
        TimeOfDay = "Day",
    },
    {
        EventID = "event.desert_well",
        FileName = "desert_well_event.nut",
        MinDistanceFromSettlement = 7,
        MustHaveOpenRosterSpace = true,
        NumberOfEmptyInventorySlots = 1,
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert", TacticalType = "DesertHills", Road = "OnRoad" },
    },
    {
        EventID = "event.dried_oasis",
        FileName = "dried_oasis_event.nut",
        MinDistanceFromSettlement = 9,
        PlayerCharacterExcluded = true,
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert", TacticalType = "DesertHills", Road = "OffRoad" },
        UnhandledLines = ["if (candidates.len() == 0)"],
    },
    {
        EventID = "event.fire_juggler",
        FileName = "fire_juggler_event.nut",
        MaxDistanceFromSettlement = 4,
        PlayerCharacterExcluded = true,
        RequiredDLC = ["Blazing Deserts"],
        SettlementMustNotBeHostile = true,
        SettlementType = "Southern",
        TimeOfDay = "Day",
    },
    {
        BackgroundRequirements = [{ background = "gladiator", minLevel = 0, maxLevel = 0 }],
        EventID = "event.gladiators_food",
        FileName = "gladiators_food_event.nut",
        RequiredDLC = ["Blazing Deserts"],
        RequiredOrigins = ["scenario.gladiators"],
        UnhandledLines = ["if (item != null && item.isItemType(this.Const.Items.ItemType.Food))", "if (item.getRawValue() >= 85)", "if (hasExquisiteFood)", "if (candidates.len() == 0)"],
    },
    {
        BackgroundRequirements = [{ background = "gladiator", minLevel = 0, maxLevel = 0 }],
        EventID = "event.gladiators_vibes",
        FileName = "gladiators_vibes_event.nut",
        RequiredDLC = ["Blazing Deserts"],
        RequiredOrigins = ["scenario.gladiators"],
        UnhandledLines = ["if (candidates.len() < 2)"],
    },
    {
        EventID = "event.gunpowder_wagon",
        FileName = "gunpowder_wagon_event.nut",
        MinimumCrowns = 2501,
        NumberOfEmptyInventorySlots = 1,
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert", TacticalType = "DesertHills", Road = "OnRoad" },
    },
    {
        EventID = "event.merchant_of_jugs",
        FileName = "merchant_of_jugs_event.nut",
        MinimumCrowns = 151,
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert", TacticalType = "DesertHills", Road = "OnRoad" },
    },
    {
        EventID = "event.pirates",
        ExcludedOrigins = ["scenario.manhunters"],
        FileName = "pirates_event.nut",
        MustHaveOpenRosterSpace = true,
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert", TacticalType = "DesertHills", Road = "OnRoad" },
    },
    {
        BackgroundRequirements = [{ background = "historian", minLevel = 2, maxLevel = 0 }, { background = "cultist", minLevel = 9, maxLevel = 0 }],
        EventID = "event.read_black_book",
        FileName = "read_black_book_event.nut",
        RequiredDLC = ["Blazing Deserts"],
        RequiredFlags = ["Lorekeeper is defeated"],
        RequiredItems = ["The Black Book"],
        UnhandledLines = ["if (bro.getSkills().hasSkill(\"trait.mad\"))", "if (candidates_historian.len() == 0 || candidates_other.len() == 0)"],
    },
    {
        EventID = "event.retired_gladiator",
        FileName = "retired_gladiator_event.nut",
        MaxDistanceFromSettlement = 4,
        MinimumCrowns = 1251,
        MustHaveOpenRosterSpace = true,
        NumberOfEmptyInventorySlots = 1,
        RequiredDLC = ["Blazing Deserts"],
        SettlementMustNotBeHostile = true,
        SettlementType = "Southern",
    },
    {
        EventID = "event.runaway_harem",
        FileName = "runaway_harem_event.nut",
        MinDistanceFromSettlement = 7,
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert", TacticalType = "DesertHills", Road = "OnRoad" },
    },
    {
        EventID = "event.sellsword_retires",
        FileName = "sellsword_retires_event.nut",
        NumberOfEmptyInventorySlots = 2,
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { Road = "OnRoad" },
    },
    {
        EventID = "event.sellsword_vs_bees",
        FileName = "sellsword_vs_bees_event.nut",
        MinDistanceFromSettlement = 6,
        PlayerCharacterExcluded = true,
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert", TacticalType = "DesertHills" },
        UnhandledLines = ["if (candidates.len() == 0)"],
    },
    {
        EventID = "event.sword_eater",
        FileName = "sword_eater_event.nut",
        MaxDistanceFromSettlement = 4,
        MinimumCrowns = 101,
        NumberOfEmptyInventorySlots = 1,
        RequiredDLC = ["Blazing Deserts", "Beasts & Exploration"],
        SettlementMustNotBeHostile = true,
        SettlementType = "Southern",
        SpecialConsiderations = ["Warriors of the North DLC & a Wildman in the roster can unlock a special Wildman interaction 1 time."],
        TimeOfDay = "Day",
    },
    {
        EventID = "event.trade_black_book",
        FileName = "trade_black_book_event.nut",
        RequiredDLC = ["Blazing Deserts"],
        RequiredFlags = ["Lorekeeper is defeated"],
        RequiredItems = ["The Black Book"],
        SpecialConsiderations = ["The Peasant Militia origin qualifies without having to read the black book."],
        UnhandledLines = ["if (bro.getSkills().hasSkill(\"trait.mad\"))", "if (candidates_mad.len() == 0)"],
    },
    {
        EventID = "event.traveler_south",
        FileName = "traveler_south_event.nut",
        MinDistanceFromSettlement = 7,
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { Road = "OnRoad", OnOrBelowYLine = 20 },
    },
    {
        EventID = "event.crisis.holywar_crucified_1",
        FileName = "holywar_crucified_1_event.nut",
        MinDistanceFromSettlement = 6,
        MustHaveOpenRosterSpace = true,
        RequiredCrises = "Holy War",
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert", TacticalType = "DesertHills" },
    },
    {
        EventID = "event.crisis.holywar_flavor_north_outside",
        FileName = "holywar_flavor_north_outside_event.nut",
        MinDistanceFromSettlement = 6,
        RequiredCrises = "Holy War",
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { BelowYLine = 70, Road = "OnRoad" },
    },
    {
        EventID = "event.crisis.holywar_flavor_north_settlement",
        FileName = "holywar_flavor_north_settlement_event.nut",
        MaxDistanceFromSettlement = 5,
        RequiredDLC = ["Blazing Deserts"],
        SettlementMustNotBeHostile = true,
        SettlementType = "Northern",
    },
    {
        EventID = "event.crisis.holywar_flavor_south_outside",
        FileName = "holywar_flavor_south_outside_event.nut",
        MinDistanceFromSettlement = 6,
        RequiredCrises = "Holy War",
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert", TacticalType = "DesertHills", Road = "OnRoad" },
    },
    {
        EventID = "event.crisis.holywar_flavor_south_settlement",
        FileName = "holywar_flavor_south_settlement_event.nut",
        MaxDistanceFromSettlement = 5,
        RequiredDLC = ["Blazing Deserts"],
        SettlementMustNotBeHostile = true,
        SettlementType = "Southern",
    },
    {
        EventID = "event.holywar_ill_southerners",
        FileName = "holywar_ill_southerners_event.nut",
        MaxDistanceFromSettlement = 20,
        MinDistanceFromSettlement = 7,
        RequiredCrises = "Holy War",
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { AboveYLine = 20 },
        TimeOfDay = "Day",
    },
    {
        EventID = "event.holywar_neutral_nomads",
        ExcludedOrigins = ["scenario.manhunters", "scenario.gladiators", "scenario.southern_quickstart"],
        FileName = "holywar_neutral_nomads_event.nut",
        MinDistanceFromSettlement = 7,
        RequiredCrises = "Holy War",
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert", TacticalType = "DesertHills", Road = "OffRoad" },
    },
    {
        EventID = "event.holywar_sand_storm",
        FileName = "holywar_sand_storm_event.nut",
        MinDistanceFromSettlement = 8,
        RequiredCrises = "Holy War",
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert" },
        TimeOfDay = "Day",
    },
    {
        EventID = "event.crisis.holy_warnings",
        FileName = "holywar_warnings_event.nut",
        MinDistanceFromSettlement = 5,
        RequiredCrises = "Holy War",
        RequiredCrisesStatus = "Warning",
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { Road = "OnRoad" },
    }
];